service: hands-free-ui-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'staging'}
  region: us-east-1
  timeout: 300
  memorySize: 2048
  environment:
    NODE_ENV: development
    MONGODB_URL: mongodb+srv://nearpadapp:WBRsqoZrz833nQoT@nearpad-cluster-1.stmpadb.mongodb.net/hands-free-ui?retryWrites=true&w=majority
    PULZE_API_KEY: "sk-FAogNPqmJzD_2BZvBFdrJHzQCvDp7U9vEjMZtFGlEPtbmp3CcARRo-Hdx__yPAQr"

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY

      - http:
          path: /{proxy+}
          method: ANY
